SET(FullMonteSW_INCLUDE_DIRS ${FullMonteSW_INCLUDE_DIR})
SET(FullMonteSW_LIBRARY_DIRS ${FullMonteSW_LIBRARY_DIR})

INCLUDE_DIRECTORIES(${FullMonteSW_INCLUDE_DIRS})
LINK_DIRECTORIES(${FullMonteSW_LIBRARY_DIRS})